### ISSUE TITLE
Will this work for CM 12.1 or CM 13 ??

### ISSUE THREAD

**Issue by deepsidhu1313** [kashifmin/android_device_micromax_a116#2]
Hi, i am trying to build CM for Sony Xperia C (c2305), do these settings and proprietary files work in latest version of CM ??

I am getting stuck at boot logo !! :P 

Thanks :)

**Comment by Preet23** [comment]
No, it won't. And you better stop the development of mt6589 since latest CM won't work however, you can boot 5.0.2 with a lot of labour.

**Comment by deepsidhu1313** [comment]
@Preet23  Thanks :smiley:  But why latest CM won't work on mt6589 ?? is there any technical reason ??
